#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat >&2 <<'EOF'
Usage: setup-monitors.sh [--force] [LEFT_OUTPUT RIGHT_OUTPUT ...]

Write a machine-local Hyprland monitor layout. With no output names, connected
outputs are ordered from left to right using their current positions. Pass names
only when that order is wrong. A repeat that would write the same file succeeds
and leaves it in place. --force replaces an existing layout.
EOF
}

force=false
outputs=()
while (($#)); do
  case "$1" in
    --force) force=true; shift ;;
    -h|--help) usage; exit 0 ;;
    -*) usage; exit 2 ;;
    *) outputs+=("$1"); shift ;;
  esac
done

for output in "${outputs[@]+"${outputs[@]}"}"; do
  if [[ ! "$output" =~ ^[A-Za-z0-9._:-]+$ ]]; then
    printf 'Invalid output name: %s\n' "$output" >&2
    exit 2
  fi
done

config_home="${XDG_CONFIG_HOME:-${HOME:?HOME is not set}/.config}"
destination="${NIX_HOME_MONITORS_FILE:-$config_home/hypr/local_monitors.lua}"

if ! command -v hyprctl >/dev/null; then
  printf 'hyprctl is required; run this command inside the Hyprland session.\n' >&2
  exit 1
fi
if ! command -v jq >/dev/null; then
  printf 'jq is required to select the best mode for each output.\n' >&2
  exit 1
fi

if ! monitor_json=$(hyprctl -j monitors all); then
  printf 'Could not query Hyprland monitors; run this command inside the Hyprland session.\n' >&2
  exit 1
fi

if ((${#outputs[@]} == 0)); then
  mapfile -t outputs < <(
    jq -r '[.[] | select(.disabled != true)] | sort_by([.x // 0, .name]) | .[].name' <<< "$monitor_json"
  )
fi

if ((${#outputs[@]} == 0)); then
  printf 'No connected outputs found.\n' >&2
  exit 1
fi

best_mode_for() {
  local output="$1"
  jq -r --arg output "$output" '.[] | select(.name == $output) | .availableModes[]' <<< "$monitor_json" |
    while IFS= read -r mode; do
      if [[ "$mode" =~ ^([0-9]+)x([0-9]+)@([0-9.]+)Hz$ ]]; then
        printf '%d %s %s\n' "$((BASH_REMATCH[1] * BASH_REMATCH[2]))" "${BASH_REMATCH[3]}" "$mode"
      fi
    done |
    sort -k1,1n -k2,2n |
    tail -n 1 |
    cut -d ' ' -f 3
}

declare -a modes=()
for output in "${outputs[@]}"; do
  best_mode=$(best_mode_for "$output")
  if [[ -z "$best_mode" ]]; then
    printf 'Output not found or has no usable modes: %s\n' "$output" >&2
    exit 1
  fi
  modes+=("$best_mode")
done

destination_dir=$(dirname "$destination")
mkdir -p "$destination_dir"
temporary=$(mktemp "$destination_dir/.local_monitors.lua.XXXXXX")
trap 'rm -f "$temporary"' EXIT

{
  cat <<'EOF'
-- Machine-local Hyprland monitor layout.
-- Generated by setup-monitors.sh; edit this file directly as needed.
-- Outputs are arranged left to right and use the highest refresh rate available
-- at each monitor's maximum resolution.

EOF

  index=0
  for output in "${outputs[@]}"; do
    if ((index == 0)); then
      position="0x0"
    else
      position="auto-right"
    fi
    cat <<EOF
hl.monitor({
    output = "$output",
    mode = "${modes[index]}",
    position = "$position",
    scale = "auto",
})

EOF
    ((index += 1))
  done
} > "$temporary"

if [[ -e "$destination" && "$force" != true ]]; then
  if cmp -s "$temporary" "$destination"; then
    printf 'Monitor layout already matches %s\n' "$destination"
    exit 0
  fi
  printf 'Keeping existing monitor layout: %s\n' "$destination"
  printf 'Re-run with --force to replace it.\n'
  exit 0
fi

chmod 0644 "$temporary"
mv "$temporary" "$destination"
trap - EXIT
printf 'Wrote %s\n' "$destination"
printf 'Reload Hyprland with: hyprctl reload\n'
